const suspects = [
    {class: "suspect" ,id: 01, image:'./Mysterium/Suspeitos/Suspeitos-1.png'},
    {class: "suspect" ,id: 02, image:'./Mysterium/Suspeitos/Suspeitos-2.png'},
    {class: "suspect" ,id: 03, image:'./Mysterium/Suspeitos/Suspeitos-3.png'},
    {class: "suspect" ,id: 04, image:'./Mysterium/Suspeitos/Suspeitos-4.png'},
    {class: "suspect" ,id: 05, image:'./Mysterium/Suspeitos/Suspeitos-5.png'},
    {class: "suspect" ,id: 06, image:'./Mysterium/Suspeitos/Suspeitos-6.png'},
    {class: "suspect" ,id: 07, image:'./Mysterium/Suspeitos/Suspeitos-7.png'},
    {class: "suspect" ,id: 08, image:'./Mysterium/Suspeitos/Suspeitos-8.png'},
    {class: "suspect" ,id: 09, image:'./Mysterium/Suspeitos/Suspeitos-9.png'},
    {class: "suspect" ,id: 10, image:'./Mysterium/Suspeitos/Suspeitos-10.png'},
    {class: "suspect" ,id: 11, image:'./Mysterium/Suspeitos/Suspeitos-11.png'},
    {class: "suspect" ,id: 12, image:'./Mysterium/Suspeitos/Suspeitos-12.png'},
    {class: "suspect" ,id: 13, image:'./Mysterium/Suspeitos/Suspeitos-13.png'},
    {class: "suspect" ,id: 14, image:'./Mysterium/Suspeitos/Suspeitos-14.png'},
    {class: "suspect" ,id: 15, image:'./Mysterium/Suspeitos/Suspeitos-15.png'},
    {class: "suspect" ,id: 16, image:'./Mysterium/Suspeitos/Suspeitos-16.png'},
    {class: "suspect" ,id: 17, image:'./Mysterium/Suspeitos/Suspeitos-17.png'},
    {class: "suspect" ,id: 18, image:'./Mysterium/Suspeitos/Suspeitos.png'},
];

const weapons = [
    {class: "weapon", id: 01, image:'./Mysterium/Armas/armas.png'},
    {class: "weapon", id: 02, image:'./Mysterium/Armas/armas-1.png'},
    {class: "weapon", id: 03, image:'./Mysterium/Armas/armas-2.png'},
    {class: "weapon", id: 04, image:'./Mysterium/Armas/armas-3.png'},
    {class: "weapon", id: 05, image:'./Mysterium/Armas/armas-4.png'},
    {class: "weapon", id: 06, image:'./Mysterium/Armas/armas-5.png'},
    {class: "weapon", id: 07, image:'./Mysterium/Armas/armas-6.png'},
    {class: "weapon", id: 08, image:'./Mysterium/Armas/armas-7.png'},
    {class: "weapon", id: 09, image:'./Mysterium/Armas/armas-8.png'},
    {class: "weapon", id: 10, image:'./Mysterium/Armas/armas-9.png'},
    {class: "weapon", id: 11, image:'./Mysterium/Armas/armas-10.png'},
    {class: "weapon", id: 12, image:'./Mysterium/Armas/armas-11.png'},
    {class: "weapon", id: 13, image:'./Mysterium/Armas/armas-12.png'},
    {class: "weapon", id: 14, image:'./Mysterium/Armas/armas-13.png'},
    {class: "weapon", id: 15, image:'./Mysterium/Armas/armas-14.png'},
    {class: "weapon", id: 16, image:'./Mysterium/Armas/armas-15.png'},
    {class: "weapon", id: 17, image:'./Mysterium/Armas/armas-16.png'},
    {class: "weapon", id: 18, image:'./Mysterium/Armas/armas-17.png'},
];

const places = [
    {class: "place", id: 01,image:'./Mysterium/Lugares/lugares.png'},
    {class: "place", id: 02,image:'./Mysterium/Lugares/lugares-1.png'},
    {class: "place", id: 03,image:'./Mysterium/Lugares/lugares-2.png'},
    {class: "place", id: 04,image:'./Mysterium/Lugares/lugares-3.png'},
    {class: "place", id: 05,image:'./Mysterium/Lugares/lugares-4.png'},
    {class: "place", id: 06,image:'./Mysterium/Lugares/lugares-5.png'},
    {class: "place", id: 07,image:'./Mysterium/Lugares/lugares-6.png'},
    {class: "place", id: 08,image:'./Mysterium/Lugares/lugares-7.png'},
    {class: "place", id: 09,image:'./Mysterium/Lugares/lugares-8.png'},
    {class: "place", id: 10,image:'./Mysterium/Lugares/lugares-9.png'},
    {class: "place", id: 11,image:'./Mysterium/Lugares/lugares-10.png'},
    {class: "place", id: 12,image:'./Mysterium/Lugares/lugares-11.png'},
    {class: "place", id: 13,image:'./Mysterium/Lugares/lugares-12.png'},
    {class: "place", id: 14,image:'./Mysterium/Lugares/lugares-13.png'},
    {class: "place", id: 15,image:'./Mysterium/Lugares/lugares-14.png'},
    {class: "place", id: 16,image:'./Mysterium/Lugares/lugares-15.png'},
    {class: "place", id: 17,image:'./Mysterium/Lugares/lugares-16.png'},
    {class: "place", id: 18,image:'./Mysterium/Lugares/lugares-17.png'},
];

const visions = [
    {id: 01, image:'./Mysterium/Sonhos/sonhos.png'},
    {id: 02, image:'./Mysterium/Sonhos/sonhos-1.png'},
    {id: 03, image:'./Mysterium/Sonhos/sonhos-2.png'},
    {id: 04, image:'./Mysterium/Sonhos/sonhos-3.png'},
    {id: 05, image:'./Mysterium/Sonhos/sonhos-4.png'},
    {id: 06, image:'./Mysterium/Sonhos/sonhos-5.png'},
    {id: 07, image:'./Mysterium/Sonhos/sonhos-6.png'},
    {id: 08, image:'./Mysterium/Sonhos/sonhos-7.png'},
    {id: 10, image:'./Mysterium/Sonhos/sonhos-9.png'},
    {id: 11, image:'./Mysterium/Sonhos/sonhos-10.png'},
    {id: 12, image:'./Mysterium/Sonhos/sonhos-11.png'},
    {id: 13, image:'./Mysterium/Sonhos/sonhos-12.png'},
    {id: 14, image:'./Mysterium/Sonhos/sonhos-13.png'},
    {id: 15, image:'./Mysterium/Sonhos/sonhos-14.png'},
    {id: 16, image:'./Mysterium/Sonhos/sonhos-15.png'},
    {id: 17, image:'./Mysterium/Sonhos/sonhos-16.png'},
    {id: 18, image:'./Mysterium/Sonhos/sonhos-17.png'},
    {id: 19, image:'./Mysterium/Sonhos/sonhos-18.png'},
    {id: 20, image:'./Mysterium/Sonhos/sonhos-19.png'},
    {id: 21, image:'./Mysterium/Sonhos/sonhos-20.png'},
    {id: 22, image:'./Mysterium/Sonhos/sonhos-21.png'},
    {id: 23, image:'./Mysterium/Sonhos/sonhos-22.png'},
    {id: 24, image:'./Mysterium/Sonhos/sonhos-23.png'},
    {id: 25, image:'./Mysterium/Sonhos/sonhos-24.png'},
    {id: 26, image:'./Mysterium/Sonhos/sonhos-25.png'},
    {id: 27, image:'./Mysterium/Sonhos/sonhos-26.png'},
    {id: 28, image:'./Mysterium/Sonhos/sonhos-27.png'},
    {id: 29, image:'./Mysterium/Sonhos/sonhos-28.png'},
    {id: 30, image:'./Mysterium/Sonhos/sonhos-29.png'},
    {id: 31, image:'./Mysterium/Sonhos/sonhos-30.png'},
    {id: 32, image:'./Mysterium/Sonhos/sonhos-31.png'},
    {id: 33, image:'./Mysterium/Sonhos/sonhos-32.png'},
    {id: 34, image:'./Mysterium/Sonhos/sonhos-33.png'},
    {id: 35, image:'./Mysterium/Sonhos/sonhos-34.png'},
    {id: 36, image:'./Mysterium/Sonhos/sonhos-35.png'},
    {id: 37, image:'./Mysterium/Sonhos/sonhos-36.png'},
    {id: 38, image:'./Mysterium/Sonhos/sonhos-37.png'},
    {id: 39, image:'./Mysterium/Sonhos/sonhos-38.png'},
    {id: 40, image:'./Mysterium/Sonhos/sonhos-39.png'},
    {id: 41, image:'./Mysterium/Sonhos/sonhos-40.png'},
    {id: 42, image:'./Mysterium/Sonhos/sonhos-41.png'},
    {id: 43, image:'./Mysterium/Sonhos/sonhos-42.png'},
    {id: 44, image:'./Mysterium/Sonhos/sonhos-43.png'},
    {id: 45, image:'./Mysterium/Sonhos/sonhos-44.png'},
    {id: 46, image:'./Mysterium/Sonhos/sonhos-45.png'},
    {id: 47, image:'./Mysterium/Sonhos/sonhos-46.png'},
    {id: 47, image:'./Mysterium/Sonhos/sonhos-47.png'},
    {id: 48, image:'./Mysterium/Sonhos/sonhos-48.png'},
    {id: 49, image:'./Mysterium/Sonhos/sonhos-49.png'},
    {id: 50, image:'./Mysterium/Sonhos/sonhos-50.png'},
    {id: 51, image:'./Mysterium/Sonhos/sonhos-51.png'},
    {id: 52, image:'./Mysterium/Sonhos/sonhos-52.png'},
    {id: 53, image:'./Mysterium/Sonhos/sonhos-53.png'},
    {id: 54, image:'./Mysterium/Sonhos/sonhos-54.png'},
    {id: 55, image:'./Mysterium/Sonhos/sonhos-55.png'},
    {id: 56, image:'./Mysterium/Sonhos/sonhos-56.png'},
    {id: 57, image:'./Mysterium/Sonhos/sonhos-57.png'},
    {id: 58, image:'./Mysterium/Sonhos/sonhos-58.png'},
    {id: 58, image:'./Mysterium/Sonhos/sonhos-59.png'},
    {id: 59, image:'./Mysterium/Sonhos/sonhos-60.png'},
    {id: 60, image:'./Mysterium/Sonhos/sonhos-61.png'},
    {id: 61, image:'./Mysterium/Sonhos/sonhos-62.png'},
    {id: 62, image:'./Mysterium/Sonhos/sonhos-63.png'},
    {id: 63, image:'./Mysterium/Sonhos/sonhos-64.png'},
    {id: 64, image:'./Mysterium/Sonhos/sonhos-65.png'},
    {id: 65, image:'./Mysterium/Sonhos/sonhos-66.png'},
    {id: 66, image:'./Mysterium/Sonhos/sonhos-67.png'},
    {id: 67, image:'./Mysterium/Sonhos/sonhos-68.png'},
    {id: 68, image:'./Mysterium/Sonhos/sonhos-69.png'},
    {id: 69, image:'./Mysterium/Sonhos/sonhos-70.png'},
    {id: 70, image:'./Mysterium/Sonhos/sonhos-71.png'},
    {id: 71, image:'./Mysterium/Sonhos/sonhos-72.png'},
    {id: 72, image:'./Mysterium/Sonhos/sonhos-73.png'},
    {id: 73, image:'./Mysterium/Sonhos/sonhos-74.png'},
    {id: 74, image:'./Mysterium/Sonhos/sonhos-75.png'},
    {id: 75, image:'./Mysterium/Sonhos/sonhos-76.png'},
    {id: 76, image:'./Mysterium/Sonhos/sonhos-77.png'},
    {id: 77, image:'./Mysterium/Sonhos/sonhos-78.png'},
    {id: 78, image:'./Mysterium/Sonhos/sonhos-79.png'},
    {id: 79, image:'./Mysterium/Sonhos/sonhos-80.png'},
    {id: 80, image:'./Mysterium/Sonhos/sonhos-81.png'},
    {id: 81, image:'./Mysterium/Sonhos/sonhos-82.png'},
    {id: 82, image:'./Mysterium/Sonhos/sonhos-83.png'},
    {id: 82, image:'./Mysterium/Sonhos/sonhos-84.png'},
];

const players = [
    {id: "blue", image:"./Mysterium/Jogadores/pic2799330.png"},
    {id: "white", image:"./Mysterium/Jogadores/pic2799331.png"},
    {id: "black", image:"./Mysterium/Jogadores/pic2799333.png"},
    {id: "yeallow", image:"./Mysterium/Jogadores/pic2799334.png"},
    {id: "violet", image:"./Mysterium/Jogadores/pic2799335.png"},
    {id: "red", image:"./Mysterium/Jogadores/pic2799336.png"},
];

const crowsData = [
    { id: 01, image:'./Mysterium/corvos/pic2866933-removebg-preview.png'},
    { id: 02, image:'./Mysterium/corvos/pic2866934-removebg-preview.png'},
    { id: 03, image:'./Mysterium/corvos/pic2866935-removebg-preview.png'},
]